
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pry1_ci;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 44;
  public static final int STRING_LITERAL = 49;
  public static final int POWER = 32;
  public static final int CHAR = 7;
  public static final int PARENTESISCIERRA = 35;
  public static final int FIN_EXPRESION = 12;
  public static final int SEMI = 38;
  public static final int GREATER_THAN_OR_EQ = 47;
  public static final int INT = 4;
  public static final int FOR = 18;
  public static final int MINUS = 29;
  public static final int GREATER_THAN = 45;
  public static final int LESS_THAN_OR_EQ = 48;
  public static final int SYS_READ = 24;
  public static final int PARENTESISABRE = 34;
  public static final int DO_WHILE = 17;
  public static final int BOOL = 3;
  public static final int PLUS = 26;
  public static final int MAIN = 22;
  public static final int IF = 13;
  public static final int LLAVESCORCHETECIERRA = 37;
  public static final int EOF = 0;
  public static final int ARREGLO = 8;
  public static final int MINUSMINUS = 43;
  public static final int RETURN = 20;
  public static final int TRUE = 9;
  public static final int SYS_PRINT = 23;
  public static final int error = 1;
  public static final int COMA = 39;
  public static final int NEGACION = 40;
  public static final int MODULO = 33;
  public static final int NULL = 21;
  public static final int EQEQ = 25;
  public static final int BREAK = 19;
  public static final int EQ = 27;
  public static final int DIVI = 30;
  public static final int TIMES = 28;
  public static final int COMENTARIO_SIMPLE = 11;
  public static final int ELSE = 14;
  public static final int NOT_EQ = 31;
  public static final int WHILE = 16;
  public static final int LLAVESCORCHETEABRE = 36;
  public static final int FLOAT = 5;
  public static final int Identificador = 2;
  public static final int CONJUNCION = 41;
  public static final int STRING = 6;
  public static final int DISYUNCION = 42;
  public static final int FALSE = 10;
  public static final int LESS_THAN = 46;
  public static final int ELIF = 15;
  public static final int INTEGER_LITERAL = 50;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Identificador",
  "BOOL",
  "INT",
  "FLOAT",
  "STRING",
  "CHAR",
  "ARREGLO",
  "TRUE",
  "FALSE",
  "COMENTARIO_SIMPLE",
  "FIN_EXPRESION",
  "IF",
  "ELSE",
  "ELIF",
  "WHILE",
  "DO_WHILE",
  "FOR",
  "BREAK",
  "RETURN",
  "NULL",
  "MAIN",
  "SYS_PRINT",
  "SYS_READ",
  "EQEQ",
  "PLUS",
  "EQ",
  "TIMES",
  "MINUS",
  "DIVI",
  "NOT_EQ",
  "POWER",
  "MODULO",
  "PARENTESISABRE",
  "PARENTESISCIERRA",
  "LLAVESCORCHETEABRE",
  "LLAVESCORCHETECIERRA",
  "SEMI",
  "COMA",
  "NEGACION",
  "CONJUNCION",
  "DISYUNCION",
  "MINUSMINUS",
  "PLUSPLUS",
  "GREATER_THAN",
  "LESS_THAN",
  "GREATER_THAN_OR_EQ",
  "LESS_THAN_OR_EQ",
  "STRING_LITERAL",
  "INTEGER_LITERAL"
  };
}

